"""Compose the drift-detection issue title + body.

Writing this issue is split across layers: Python assembles the markdown (logic),
bash runs ``gh issue create`` (orchestration, per DEV_RULES #2).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

from .cache_comparator import CacheComparison, SectionDiff

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class DriftReport:
    pbi_id: int
    attachment_name: str
    comparison: CacheComparison
    section_diff: SectionDiff
    fresh_size: int
    cached_size: int | None
    image_count: int

    def title(self, doc_name: str) -> str:
        return (
            f"chore(fds): new version of {doc_name} attached to PBI #{self.pbi_id} "
            f"— update domain cache"
        )

    def body(self, doc_name: str) -> str:
        cached_md5 = self.comparison.cached_md5 or "(no cached version)"
        cached_size = "n/a" if self.cached_size is None else f"{self.cached_size} bytes"
        size_delta = (
            "n/a"
            if self.cached_size is None
            else f"{self.fresh_size - self.cached_size:+d} bytes"
        )
        added = "\n".join(f"- {s}" for s in self.section_diff.added) or "  (none)"
        removed = "\n".join(f"- {s}" for s in self.section_diff.removed) or "  (none)"
        return (
            f"## Drift detected on PBI #{self.pbi_id}\n\n"
            f"The attachment `{self.attachment_name}` on PBI #{self.pbi_id} has a "
            "different MD5 than the cached copy in the `fivepoints` domain. The cache "
            "is read-only; update it via PR.\n\n"
            "### MD5\n"
            f"- **Cached:** `{cached_md5}` ({cached_size})\n"
            f"- **Fresh:**  `{self.comparison.fresh_md5}` ({self.fresh_size} bytes)\n"
            f"- **Delta:**  {size_delta}\n\n"
            "### Section delta\n"
            "**Added sections (present in fresh, missing from cache):**\n"
            f"{added}\n\n"
            "**Removed sections (present in cache, missing from fresh):**\n"
            f"{removed}\n\n"
            f"**Image count in fresh:** {self.image_count}\n\n"
            "### Next steps\n"
            "1. Review the drift above.\n"
            "2. Update `domain/knowledge/FDS_<NAME>.docx` + extracted section markdown + "
            "IMAGE_INDEX via PR.\n"
            "3. Do not overwrite the cache automatically — changes flow through review.\n\n"
            "_Generated by `claire fivepoints ado-fetch-attachments --auto-issue`._\n"
        )


def write_body_to_file(body: str, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    return path
